### ISSUE TITLE
There is no way to toggle show/hide FTB chunks on the map

### ISSUE THREAD

**Issue by Kairi-lol** [TeamJM/journeymap-additions#5]
Forge Ver 1.18.2 - 40.1.31
Journey map Ver 1.18.2-5.8.4

I want to be able to toggle visibility for the FTB Chunks rendering on the minimap/main map but there is no way to do so. I have looked around but I cannot find a way to get it to disable render except when I disable the entire map from rendering.

**Comment by mysticdrew** [comment]
This mod has nothing to do with FTBChunks.

**Comment by Kairi-lol** [comment]
my bad I was looking for JourneyMap Integration, not addons my apologies!
